## List stream raw of all datasets in yaml format
LIST_STREAM_RAW:
  neuraivn:
    ## Phone - Continuous
    - ACC # Accelerometer
    - GYRO # Gyroscope
    - BATTERY # Battery
    - NETWORK # Network
    
    ## Phone - Event
    - APPSTATE # App state
    
    ## Wearable - Epoch Timeseries
    - AZMTS # active zone minutes time series
    - ATS # Activity time series
    - HRTS # Heart rate time series

    ## Wearable - Summaries
    - BREATHINGRATE
    - HRV
    - SKINTEMP
    - SPO2
    - SLEEP

    ## REPORT
    - DAILYSURVEY
    - MOODLOG

    ## Not use this
    # - PHQ9
    # - GAD7


SEED: 42
TEST_SIZE: 0.15
VAL_SIZE_FROM_DEV: 0.15 # the result of 0.15 / (1 - 0.15)


